config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users', to: 'users#index'
  delete '/users/:id/destroy', to: 'users#destroy', as: :destroy_user
  get '/users/:id', to: 'users#show', as: :user
  get '/users/:id/edit', to: 'users#edit', as: :edit_user
  patch '/users/:id', to: 'users#update', as: :update_user

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/password_resets/new', to: 'password_resets#new', as: :new_password_reset
  post '/password_resets', to: 'password_resets#create', as: :password_resets
  get '/password_resets/:token/edit', to: 'password_resets#edit', as: :edit_password_reset
  patch '/password_resets/:token', to: 'password_resets#update', as: :password_reset

  get '/posts/new', to: 'posts#new', as: :new_post
  post '/posts/new', to: 'posts#create'
  delete '/posts/:id/destroy', to: 'posts#destroy', as: :destroy_post
  get '/posts/:id', to: 'posts#show', as: :post
  get '/posts/:id/edit', to: 'posts#edit', as: :edit_post
  patch '/posts/:id', to: 'posts#update', as: :update_post

  post '/posts/:id/like', to: 'likes#create', as: :like
  delete '/posts/:id/unlike', to: 'likes#destroy', as: :unlike

  root "home#index"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :post_id, uniqueness: { scope: :user_id }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :is_logged_in, only: [:index, :create, :destroy]
  before_action :is_user, only: [:index]

  def create
    @user = current_user
    @post = Post.find(params[:id])

    if @user && @post
      like = Like.where(user_id: @user.id, post_id: @post.id).first
      if like.nil?
        @like = Like.create(user_id: @user.id, post_id: @post.id)
      end
    end

    if @like
      respond_to do |format|
        format.js { render layout: false }
      end
    else
      head :no_content
    end
  end

  def destroy
    @user = current_user
    @post = Post.find(params[:id])

    if @user && @post
      @like = Like.where(user_id: @user.id, post_id: @post.id).first
      if @like
        @like.destroy
      end
    end

    if @like
      respond_to do |format|
        format.js { render layout: false }
      end
    else
      head :no_content
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like_button.erb
<div class='js-like-<%= post.id %> text-left col'>
  <% if current_user && Like.where(user_id: current_user.id, post_id: post.id).size > 0 %>
    <%= link_to unlike_path(post), method: :delete, remote: true, title: 'Unlike' do %>
      <%= icon('fas', 'heart', class: 'fa-2x icon-selected') %>
    <% end %>
  <% elsif current_user %>
    <%= link_to like_path(post), method: :post, remote: true, title: 'Like' do %>
      <%= icon('far', 'heart', class: 'fa-2x icon-unselected') %>
    <% end %>
  <% end %>
</div>

app/views/likes/create.js.erb
$('.js-like-<%= @post.id %>').replaceWith("<%= escape_javascript(render(partial: 'likes/like_button', locals: {post: @post})) %>");

var eventLabel = '<%= @post.title %>';
var eventUrl = '<%= post_url(@post) %>';
var likeDetails = {
    'postTitle': '<%= @post.title&.downcase %>',
    'postAuthor': '<%= @post.author&.downcase %>',
    'postCategory': '<%= @post.category&.downcase %>',
    'postPublishDate': '<%= @post.created_at.to_date %>',
    'postId': '<%= @post.id %>'
};

GA_trackLike(eventLabel, eventUrl, likeDetails);

app/views/likes/destroy.js.erb
$('.js-like-<%= @post.id %>').replaceWith("<%= escape_javascript(render(partial: 'likes/like_button', locals: {post: @post})) %>");