config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users', to: 'users#index'
  delete '/users/:id/destroy', to: 'users#destroy', as: :destroy_user
  get '/users/:id', to: 'users#show', as: :user
  get '/users/:id/edit', to: 'users#edit', as: :edit_user
  patch '/users/:id', to: 'users#update', as: :update_user

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/password_resets/new', to: 'password_resets#new', as: :new_password_reset
  post '/password_resets', to: 'password_resets#create', as: :password_resets
  get '/password_resets/:token/edit', to: 'password_resets#edit', as: :edit_password_reset
  patch '/password_resets/:token', to: 'password_resets#update', as: :password_reset

  get '/posts/new', to: 'posts#new', as: :new_post
  post '/posts/new', to: 'posts#create'
  delete '/posts/:id/destroy', to: 'posts#destroy', as: :destroy_post
  get '/posts/:id', to: 'posts#show', as: :post
  get '/posts/:id/edit', to: 'posts#edit', as: :edit_post
  patch '/posts/:id', to: 'posts#update', as: :update_post

  post '/posts/:id/like', to: 'likes#create', as: :like
  delete '/posts/:id/unlike', to: 'likes#destroy', as: :unlike

  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :reset_token
  before_save :downcase_email

  validates :username,
            presence: true,
            length: { maximum: 50 },
            uniqueness: { case_sensitive: false }

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            length: { maximum: 255 },
            uniqueness: { case_sensitive: false },
            format: { with: EMAIL_REGEX }

  has_secure_password
  validates :password,
            presence: true,
            length: { minimum: 8 },
            allow_nil: true

  has_many :likes, dependent: :destroy



  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    if digest.nil?
      return false
    else
      BCrypt::Password.new(digest).is_password?(token)
    end
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest:  User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_logged_in, only: [:index, :edit, :update, :destroy]
  before_action :is_user, only: [:edit, :update]
  before_action :is_admin, only: [:destroy]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def show
    @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      session[:registration_event] = {status: 'success', user_type: 'registered', user_id: @user.id, method: 'on-site'}
      redirect_to root_url
    else
      session[:registration_event] = {status: 'fail', user_type: 'unregistered', method: 'on-site', error: 'form errors'}
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :password,
                                 :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

  def gravatar_url_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  end

end

app/views/users/edit.erb
<% provide(:title, "Edit user") %>

<div class="row justify-content-center">
  <div class="col-md-6">

    <div class="card">
      <div class="card-header">
        <h3 class="text-center">Update your profile</h3>
      </div>
      <div class="card-body">
        <%= form_for(@user, url: update_user_path) do |f| %>
          <%= render 'shared/error_messages', obj: @user %>
          <div class="form-group">
            <%= gravatar_for @user %>
            <a href="http://gravatar.com/emails" target="_blank">change</a>
          </div>

          <div class="form-group">
            <%= f.label :username %>
            <%= f.text_field :username, class: 'form-control js-event-form-field', data: {event_form_field_value: 'edit - username'} %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control js-event-form-field', data: {event_form_field_value: 'edit - email'} %>
          </div>

          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control js-event-form-field', data: {event_form_field_value: 'edit - password'} %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control js-event-form-field', data: {event_form_field_value: 'edit - password confirmation'} %>
          </div>
          <%= f.submit "Save changes", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.erb
<% provide(:title, 'All users') %>

<div class="row justify-content-center">
  <div class="col-md-8">

    <h1 class="text-center">All users</h1>

    <%= paginate @users %>
    <ul class="list-unstyled">
      <hr>
      <% @users.each do |user| %>
        <li class="media" style="">
          <%= image_tag(gravatar_url_for(user), alt: user.username, class: "mr-3")%>
          <div class="media-body">
            <h5 class="mt-0 mb-1"><%= link_to user.username, user %></h5>
            <% if current_user.admin? && !current_user?(user) %>
              <%= link_to "delete", destroy_user_path(user), method: :delete,
                          data: { confirm: "You sure?" } %>
            <% end %>    </div>
        </li>
        <hr>
      <% end %>
    </ul>
    <%= paginate @users %>

  </div>
</div>

app/views/users/new.erb
<% provide(:title, 'Sign up') %>

<div class="row justify-content-center">
  <div class="col-md-6">

    <div class="card">
      <div class="card-header">
        <h3 class="text-center">Sign up</h3>
      </div>
      <div class="card-body">
        <%= form_for(@user, url: signup_path) do |f| %>
          <%= render 'shared/error_messages', obj: @user %>

          <div class="form-group">
            <%= f.label :username %>
            <%= f.text_field :username, class: 'form-control js-event-form-field', data: {event_form_field_value: 'sign up - username'} %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control js-event-form-field', data: {event_form_field_value: 'sign up - email'} %>
          </div>

          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control js-event-form-field', data: {event_form_field_value: 'sign up - password'} %>
            <small class="form-text text-muted">Must be at least 8 characters long</small>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control js-event-form-field', data: {event_form_field_value: 'sign up - password confirmation'} %>
          </div>

          <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/users/show.erb
<% provide(:title, @user.username) %>

<div class="row justify-content-center">
  <aside class="col-md-8">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.username %>
      </h1>
    </section>
  </aside>
</div>

<div class="row justify-content-center">
  <div class="col-md-8">
    <%= paginate @likes %>

    <ul class="list-unstyled">
      <% @likes.each do |like| %>
        <li class="post-item">
          <%= render "posts/post", post: like.post %>
        </li>
      <% end %>
    </ul>

    <%= paginate @likes %>
  </div>
</div>