config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users', to: 'users#index'
  delete '/users/:id/destroy', to: 'users#destroy', as: :destroy_user
  get '/users/:id', to: 'users#show', as: :user
  get '/users/:id/edit', to: 'users#edit', as: :edit_user
  patch '/users/:id', to: 'users#update', as: :update_user

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/password_resets/new', to: 'password_resets#new', as: :new_password_reset
  post '/password_resets', to: 'password_resets#create', as: :password_resets
  get '/password_resets/:token/edit', to: 'password_resets#edit', as: :edit_password_reset
  patch '/password_resets/:token', to: 'password_resets#update', as: :password_reset

  get '/posts/new', to: 'posts#new', as: :new_post
  post '/posts/new', to: 'posts#create'
  delete '/posts/:id/destroy', to: 'posts#destroy', as: :destroy_post
  get '/posts/:id', to: 'posts#show', as: :post
  get '/posts/:id/edit', to: 'posts#edit', as: :edit_post
  patch '/posts/:id', to: 'posts#update', as: :update_post

  post '/posts/:id/like', to: 'likes#create', as: :like
  delete '/posts/:id/unlike', to: 'likes#destroy', as: :unlike

  root "home#index"
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title,
            presence: true,
            length: { maximum: 255 }

  validates :author,
            presence: true,
            length: { maximum: 255 }

  validates :description,
            presence: true,
            length: { maximum: 255 }

  validates :category,
            presence: true

  validates :image,
            presence: true

  has_many :likes, dependent: :destroy

  scope :newest_first, -> { order(created_at: :desc) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_logged_in, only: [:new, :create, :edit, :update, :destroy]
  before_action :is_admin, only: [:new, :create, :edit, :update, :destroy]

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post deleted"
    redirect_to root_url
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:info] = "Post saved"
      redirect_to post_url(@post)
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Post updated"
      redirect_to post_url(@post)
    else
      render 'edit'
    end
  end


  private

  def post_params
    params.require(:post).permit(:title, :description, :category,
                                 :author, :image)
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_meta_tags.erb
<!-- Dynamic General Tags -->
<meta name="keywords" content="<%= post.category %>" />
<meta name="description" content="<%= post.description %>" />

<!-- Feature Item Sharing -->
<!-- Facebook Open Graph Tags -->
<meta property="og:url" content="<%= post_url(post) %>" />
<meta property="og:type" content="article" />
<meta property="og:title" content="<%= post.title %>" />
<meta property="og:image" content="<%= image_url(post.image) %>" />
<meta property="og:image:height" content="<%= post.image_width %>" />
<meta property="og:image:width" content="<%= post.image_height %>" />
<meta property="og:description" content="<%= post.description %>" />
<meta property="og:site_name" content="Look At My Cat" />

<!-- Dynamic Twitter Card Meta Tags -->
<meta name="twitter:card" content="photo">
<meta name="twitter:site" content="Look At My Cat">
<meta name="twitter:url" content="<%= post_url(post) %>">
<meta name="twitter:title" content="<%= post.title %>">
<meta name="twitter:description" content="<%= post.description %>">
<meta name="twitter:image" content="<%= image_url(post.image) %>">

app/views/posts/_post.erb
<div class="card js-share-item"
     data-url="<%= post_url(post) %>"
     data-id="<%= post.id %>"
     data-date="<%= post.created_at.to_date %>"
     data-formatted-date="<%= post.created_at.strftime('%B %d, %Y') %>"
     data-author="<%= post.author %>"
     data-title="<%= post.title %> | Look At My Cat"
     data-category="<%= post.description %>"
     data-description="<%= post.description %>"
     data-image="<%= image_url(post.image) %>">

  <% if current_user&.admin? %>
    <div class="card-body text-right">

      <%= link_to destroy_post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, class: "card-link", title: "Delete" do %>
        <%= icon('far', 'trash-alt', class: 'fa-2x text-danger') %>
      <% end %>

      <%= link_to edit_post_path(post), class: "card-link text-primary", title: "Edit" do %>
        <%= icon('far', 'edit', class: 'fa-2x') %>
      <% end %>

    </div>
  <% end %>

  <%= image_tag post.image.url, class: "card-img-top" %>


    <div class="card-body card-body-interactions">
      <div class="row">
        <% if current_user%>
          <%= render partial: 'likes/like_button', locals: {post: post} %>
        <% end %>
        <%= render partial: 'posts/share_buttons' %>
      </div>
    </div>

  <div class="card-body">
    <h5 class="card-title"><%= link_to post.title, post_url(post), data: {link_type: 'post-title'} %></h5>
    <p class="card-text"><%= post.description %></p>
  </div>
</div>

app/views/posts/_share_buttons.erb
<div class="js-social-share-container text-right col">
  <%= link_to '#', class: "js-facebook js-share-button", title: "Share on Facebook" do %>
    <%= icon('fab', 'facebook', class: 'fa-2x icon-unselected') %>
  <% end %>
  <%= link_to '#', class: "js-twitter js-share-button", title: "Share on Twitter" do %>
    <%= icon('fab', 'twitter', class: 'fa-2x icon-unselected') %>
  <% end %>

</div>

app/views/posts/edit.erb
<% provide(:title, 'Edit post') %>
<div class="row justify-content-center">
  <div class="col-md-8">

    <div class="card">
      <div class="card-header">
        <h3 class="text-center">Edit post</h3>
      </div>
      <div class="card-body">
        <%= form_for(@post, url: update_post_path) do |f| %>
          <%= render 'shared/error_messages', obj: @post %>

          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :author %>
            <%= f.text_field :author, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :category %>
            <%= f.text_field :category, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image, class: 'form-control' %>
            <%= image_tag @post.image.url, class: "img-fluid" %>
          </div>

          <%= f.submit "Update", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.erb
<% provide(:title, 'Create new post') %>

<div class="row justify-content-center">
  <div class="col-md-8">

    <div class="card">
      <div class="card-header">
        <h3 class="text-center">Create new post</h3>
      </div>
      <div class="card-body">
        <%= form_for(@post, url: new_post_path) do |f| %>
          <%= render 'shared/error_messages', obj: @post %>

          <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
          </div>

          <div class="form-group">
          <%= f.label :author %>
          <%= f.text_field :author, class: 'form-control' %>
          </div>

          <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
          </div>

          <div class="form-group">
          <%= f.label :category %>
          <%= f.text_field :category, class: 'form-control' %>
          </div>

          <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image, class: 'form-control' %>
          </div>

          <%= f.submit "Create", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.erb
<% provide(:title, @post.title) %>

<% content_for :meta_tags do %>
  <%= render partial: 'posts/meta_tags', locals: {post: @post} %>
<% end %>

<div class="row justify-content-center">
  <div class="col-md-8">
    <%= render "posts/post", post: @post %>
  </div>
</div>