config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users', to: 'users#index'
  delete '/users/:id/destroy', to: 'users#destroy', as: :destroy_user
  get '/users/:id', to: 'users#show', as: :user
  get '/users/:id/edit', to: 'users#edit', as: :edit_user
  patch '/users/:id', to: 'users#update', as: :update_user

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/password_resets/new', to: 'password_resets#new', as: :new_password_reset
  post '/password_resets', to: 'password_resets#create', as: :password_resets
  get '/password_resets/:token/edit', to: 'password_resets#edit', as: :edit_password_reset
  patch '/password_resets/:token', to: 'password_resets#update', as: :password_reset

  get '/posts/new', to: 'posts#new', as: :new_post
  post '/posts/new', to: 'posts#create'
  delete '/posts/:id/destroy', to: 'posts#destroy', as: :destroy_post
  get '/posts/:id', to: 'posts#show', as: :post
  get '/posts/:id/edit', to: 'posts#edit', as: :edit_post
  patch '/posts/:id', to: 'posts#update', as: :update_post

  post '/posts/:id/like', to: 'likes#create', as: :like
  delete '/posts/:id/unlike', to: 'likes#destroy', as: :unlike

  root "home#index"
end

app/views/layouts/_gtm.erb
<script>
    window.dataLayer = window.dataLayer || [];
    window.dataLayer.push({
        'event': 'dataLayer-loaded',
        'userType': '<%= current_user ? 'registered' : 'unregistered' %>',

        <% if @post&.created_at %>
        'postTitle': '<%= @post.title&.downcase %>',
        'postAuthor': '<%= @post.author&.downcase %>',
        'postCategory': '<%= @post.category&.downcase %>',
        'postPublishDate': '<%= @post.created_at&.to_date %>',
        'postId': '<%= @post.id %>'
        <% end %>
    });
</script>

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-KR4ZLJX');</script>
<!-- End Google Tag Manager -->

<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KR4ZLJX" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<% registration_event = get_ga_event(:registration_event) %>
<% if registration_event %>
  <div id="registration-event" class="js-event-registration"
       data-event-registration-status="<%= registration_event['status'] %>"
       data-event-registration-user-type="<%= registration_event['user_type'] %>"
       data-event-registration-user-id="<%= registration_event['user_id'] ? registration_event['user_id'] : 'n/a' %>"
       data-event-registration-method="<%= registration_event['method'] %>"
       data-event-registration-error="<%= registration_event['error'] ? registration_event['error'] : 'n/a' %>" >
  </div>
  <% clear_ga_event(:registration_event) %>
<% end %>


<% login_event = get_ga_event(:login_event) %>
<% if login_event %>
  <div id="login-event" class="js-event-login"
       data-event-login-status="<%= login_event['status'] %>"
       data-event-login-user-type="<%= login_event['user_type'] %>"
       data-event-login-user-id="<%= login_event['user_id'] ? login_event['user_id'] : 'n/a' %>"
       data-event-login-method="<%= login_event['method'] %>"
       data-event-login-error="<%= login_event['error'] ? login_event['error'] : 'n/a' %>" >
  </div>
  <% clear_ga_event(:login_event) %>
<% end %>

app/views/layouts/_meta_tags.erb
<!--- MOBILE SCALE -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5.0, minimum-scale=1, user-scalable=yes"/>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8">
<meta name='HandheldFriendly' content='True' />
<meta name='MobileOptimized' content='320' />

<%= csrf_meta_tags %>

<% if content_for :meta_tags %>
  <%= yield :meta_tags %>
<% else %>
  <meta name="keywords" content="cats" />
  <meta name="description" content="A sample app demo of basic GTM setup...and pictures of my cat">
<% end %>

app/views/layouts/application.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

  <%= render 'layouts/meta_tags' %>

  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= render "layouts/gtm" %>
</head>


<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <%= link_to "Look At My Cat", root_path, class: "navbar-brand", data: {link_type: 'header-nav-tier-1'} %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto justify-content-end">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link", data: {link_type: 'header-nav-tier-1'} %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link", data: {link_type: 'header-nav-tier-1'} %>
        </li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <%= link_to "Create post", new_post_path, class: "nav-link", data: {link_type: 'header-nav-tier-1'} %>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item", data: {link_type: 'header-nav-tier-2'} %>
              <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item", data: {link_type: 'header-nav-tier-2'} %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item", data: {link_type: 'header-nav-tier-2'} %>
            </div>
          </li>
        <% else %>
          <%= link_to "Sign up", signup_path, class: "nav-link", data: {link_type: 'header-nav-tier-1'} %>
          <%= link_to "Log in", login_path, class: "nav-link", data: {link_type: 'header-nav-tier-1'} %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-10">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</div>

<%= javascript_include_tag 'application' %>

</body>
</html>